### ISSUE TITLE
Redis OM .NET documentation

### ISSUE THREAD

**Issue by mickvikt** [redis-stack/redis-stack-docs#207]
I wanted to suggest to specify in the documentation, that the format of the connection string for Redis.OM is `redis://user:password@host:port`.

It baffled me for quite some time, because I was just trying to paste the connection string from the connection string, given in Azure Cache for Redis settings.

In this case, since the user name is not being used, the format becomes `redis://:password@host:port` (note the colon before password)

By the way, it would also to make sense near the demo app, that RediSearch module is needed for it to work.

**Comment by dwdougherty** [comment]
Hello Viktorus. Thank you very much for the suggestion.

**Comment by dwdougherty** [comment]
I'm attaching two screenshots depicting the updated content. Look good?
![om-net-1](https://github.com/redis-stack/redis-stack-docs/assets/1371932/53dbb8bb-e3b5-4966-b597-c00fe6a125b5)
![om-net-2](https://github.com/redis-stack/redis-stack-docs/assets/1371932/4fd472ce-9af8-47d7-8eee-95315b936548)
