### ISSUE TITLE
Run Redis Stack on Docker，The configuration file does not work

### ISSUE THREAD

**Issue by zaohuayudie** [redis-stack/redis-stack-docs#33]
The configuration file does not work
env: linux os 7

I use this command:
docker run -d --privileged=true -p 6380:6380 -v /etc/redis.conf:/etc/redis-stack-service.conf -v /local-data:/data --name redis-stack-server redis/redis-stack-server:latest

docker logs containerid
print docker start xxxx, database /var/....

/etc/redis.conf
port 6380
requirepass xxxxx
loadmodule xxxx
bind 0.0.0.0

But I use redis-CLI login directly in Docker

> info Server

Tcp_port still is 6387
config_file is empty

Later I tried using environment variables and it worked well，so the configuration would be tedious。Could you please help me see what the problem is with using config file?

**Comment by chayim** [comment]
@zaohuayudie You actually want to redirect the port on the docker side. Here's an example - binding redis stack to port _12345_ locally. Note the left hand side of the port map is your local port, whereas the right-hand side, is the port within the docker:

```
docker run -p 12345:6379 redis/redis-stack-server:latest
```

Connection Example
```
> redis-cli  -p 12345
127.0.0.1:12345> ping
PONG
```
